spring:

  application:
    name: product-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:


  datasource:
    driver-class-name: org.postgresql.Driver
    username: jzargo
    password:  root123
    url: jdbc:postgresql://localhost:5432/productdb
