package com.jzargo.leaderboardmicroservice.entity;

public enum SagaStep {
    INITIATED,
    LEADERBOARD_CREATE,
    OPTIONAL_EVENTS_CREATE,
    USER_PROFILE_UPDATE,
    COMPLETE,
    COMPENSATE_USER_PROFILE,
    COMPENSATE_OPTIONAL_EVENT,
    COMPENSATE_LEADERBOARD,
    FAILED,
    DELETED
}
