DO
$body$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = 'jzargo'
   ) THEN
      CREATE ROLE jzargo WITH LOGIN PASSWORD 'root333';
   END IF;

   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = 'debezium'
   ) THEN
      CREATE ROLE debezium WITH LOGIN PASSWORD 'dbz123' REPLICATION;
   END IF;
END
$body$;

GRANT CONNECT ON DATABASE generaldb TO jzargo, debezium;
GRANT ALL PRIVILEGES ON DATABASE generaldb TO jzargo, debezium;

\connect scoresdb
GRANT CONNECT ON DATABASE scoresdb TO jzargo;
GRANT ALL PRIVILEGES ON DATABASE scoresdb TO jzargo;
GRANT USAGE ON SCHEMA public TO jzargo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO jzargo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO jzargo;

\connect usersdb
GRANT CONNECT ON DATABASE usersdb TO jzargo;
GRANT ALL PRIVILEGES ON DATABASE usersdb TO jzargo;
GRANT USAGE ON SCHEMA public TO jzargo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO jzargo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO jzargo;

\connect analyticsdb
GRANT CONNECT ON DATABASE analyticsdb TO jzargo;
GRANT ALL PRIVILEGES ON DATABASE analyticsdb TO jzargo;
GRANT USAGE ON SCHEMA public TO jzargo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO jzargo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jzargo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO jzargo;

\connect scoresdb
GRANT CONNECT ON DATABASE scoresdb TO debezium;
GRANT ALL PRIVILEGES ON DATABASE scoresdb TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO debezium;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO debezium;

\connect usersdb
GRANT CONNECT ON DATABASE usersdb TO debezium;
GRANT ALL PRIVILEGES ON DATABASE usersdb TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO debezium;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO debezium;

