FROM eclipse-temurin:21-jdk-jammy as build

WORKDIR application

ARG JAR_FILE=build/libs/*-application.jar

COPY ${JAR_FILE} application.jar

RUN java -Djarmode=layertools -jar application.jar extract


FROM eclipse-temurin:21-jre-jammy

WORKDIR application

COPY --from=build application/dependencies/ ./
COPY --from=build application/spring-boot-loader/ ./
COPY --from=build application/snapshot-dependencies/ ./
COPY --from=build application/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.jarLauncher"]
