spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scoringdb
    driver-class-name: org.postgresql.Driver
    username: jzargo
    password: root333
  kafka:
    consumer:
      bootstrap-servers: localhost:9090,localhost:9092
      group-id: scoring-group
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging*"
  application:
    name: ScoringMicroservice
